# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel.
version: 2.13-dev-{build}

clone_folder: C:\projects\eccube2

cache:
  - '%LOCALAPPDATA%\Composer\files'

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

environment:
  global:
    USER: "postgres" 
    DBNAME: "myapp_test"
    DBPASS: "Password12!"
    DBUSER: "postgres"
    BASE_DIR: "C:/projects/ec-cube"

  matrix:
  - db: postgresql
    provider: postgresql

services:
  - iis  
  - postgresql93

# Install scripts. (runs after repo cloning)
install:
  # Set MySQL.
  #- cp tests/my.cnf c:\
  #- SET PATH=C:\Program Files\MySql\MySQL Server 5.7\bin\;%PATH%
  # Set postgresql.
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  # Set bash.
  #- cinst mingw-get
  #- set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  #- mingw-get install mingw-developer-toolkit
  ## Set PHP.
  - cinst php --version 5.6.40 --allow-empty-checksums
  - SET PATH=C:\tools\php56\;%PATH%
  - cd C:\tools\php56
  - copy php.ini-production php.ini
  - echo date.timezone="Asia/Tokyo" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_mysql.dll >> php.ini
  - echo extension=php_pgsql.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo output_buffering = Off >> php.ini
  - echo default_charset = UTF-8 >> php.ini
  - echo mbstring.language = Japanese >> php.ini
  - echo mbstring.encoding_translation = On >> php.ini
  - echo mbstring.http_input = UTF-8 >> php.ini
  - echo mbstring.http_output = pass >> php.ini
  - echo mbstring.internal_encoding = UTF-8 >> php.ini
  - cd C:\projects\eccube2
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar install

# Don't actually build.
build: off

before_test:
  - bash eccube_install.sh appveyor
  - cp tests/require.php.jenkins tests/require.php
    
test_script:
  - vendor\bin\phpunit.bat
